name: job_platform_mobile
description: Мобильное приложение для платформы вакансий
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter